[#15] [UI] As a user, I can see the global feeds from the home screen when not logged in
nimblehq/nimble-medium-ios pull request #125
Opened 2021-09-06 07:32 UTC by markgravity

Resolved #15

## What happened

Create feeds UI in Home screen

## Insight

- Added dummy models: `DummyProfile`, `DummyArticle` to show dummy feed data (will be removed in Integrate task)
- FXIME: Loading avatar from an URL cause UI is blocked

## Proof Of Work

https://user-images.githubusercontent.com/17875522/132177283-a2640846-9479-4d75-87cc-468c570ef014.mov

2021-09-07 03:01 UTC, minhnimble reviewed
Please fix conflicts on this PR as well 🛠🦀

2021-09-07 03:01 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRow.swift
> +            .frame(width: 50, height: 50)
missing `.0` here for width and height

2021-09-07 09:25 UTC, markgravity commented on NimbleMedium/Resources/Assets.xcassets/Profile/default-avatar.imageset/Contents.json
> +  ],
@minhnimble you mean pdf format or just `1x`? 🤔

2021-09-08 02:18 UTC, minhnimble commented on NimbleMedium/Resources/Assets.xcassets/Profile/default-avatar.imageset/Contents.json
> +  ],
ah I mean you can provide a single image, can be `2x` or `3x` version or a pdf file, and set the image to single scale like other images setup there as follow
<img width="1083" alt="Screen Shot 2021-09-08 at 09 16 12" src="https://user-images.githubusercontent.com/70877098/132435575-3efcb1cd-2f64-4ec5-a312-174682056047.png">

2021-09-09 02:43 UTC, markgravity commented on NimbleMedium/Resources/Assets.xcassets/Profile/default-avatar.imageset/Contents.json
> +  ],
@minhnimble if we use single scale for png, small device may have to use big image and affect to performance 🤔

2021-09-09 03:01 UTC, minhnimble commented on NimbleMedium/Resources/Assets.xcassets/Profile/default-avatar.imageset/Contents.json
> +  ],
@markgravity then please find a vector image here, providing 3 versions seems no longer an optimal choice with redundancy and cause huge app size increase later on the more we have these asset 🙏

Ref.: https://medium.com/@CoderLyn/3-reasons-why-vector-assets-are-superior-to-bitmap-assets-4028261fd488

2021-09-09 03:22 UTC, markgravity commented on NimbleMedium/Resources/Assets.xcassets/Profile/default-avatar.imageset/Contents.json
> +  ],
@minhnimble let's me replace it with pdf, but for more information it wont affect to app size 😁 
Btw, I guess they will `Slicing` our pdf into same kind of `@2x, @3x..` when we archive and upload it into AppStore 🤔 
```
Slicing: Here is what Apple document says about it.
Slicing is the process of creating and delivering variants of the app bundle for different target devices. A variant contains only the executable architecture and resources that are needed for the target device. You continue to develop and upload full versions of your app to App Store Connect. The App Store will create and deliver different variants based on the devices your app supports. This works only on iOS 9 and later, the older will still be getting the Universal binary.
```

2021-09-09 03:46 UTC, minhnimble commented on NimbleMedium/Resources/Assets.xcassets/Profile/default-avatar.imageset/Contents.json
> +  ],
@markgravity yeah probably they will do that for `Slicing`. But again, if we just provide the bitmap assets and in the future we have to support 4x, 5x, we will have to go back and add more images, why don't we just let the Apple system do it for us 😁

2021-09-09 06:30 UTC, minhnimble approved these changes
LGTM 🚀

2021-09-10 02:42 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
> +// swiftlint:disable file_types_order
do we need this line? can we fix it?

2021-09-10 02:45 UTC, markgravity commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
> +// swiftlint:disable file_types_order
@minhnimble after we do this one 
```
// TODO: Remove dummy model in Integrate
```
we can remove this disable 🤪

2021-09-10 03:13 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
> +// swiftlint:disable file_types_order
oh yeee 👍

2021-09-10 05:55 UTC, suho requested changes

2021-09-10 05:55 UTC, suho commented on NimbleMedium/Sources/Constants/Constants+String.swift
> +    static let articleDateFormat: String = "MMMM dd, yyyy"
Please define this with a static date formatter, for example:

```swift
extension DateFormatter {

    static let monthDayYear = DateFormatter(with: "MMMM dd, yyyy")

    convenience init(with format: String) {
        self.init()
        dateFormat = format
    }
}
```

2021-09-10 05:55 UTC, suho commented on NimbleMedium/Sources/Domain/Entities/Article.swift
> +        return formatter.string(from: updatedAt)
Please use a static date formatter instead of initing it every time you call `formattedUpdatedAt`.
Also, I prefer using `DateFormatter` in View Model. Different screens can use different formats.

2021-09-10 05:55 UTC, suho commented on NimbleMedium/Sources/Domain/Entities/Article.swift
> +protocol Article {
Next time, I prefer you to create the `Backend` task first. You will create models based on the response.

2021-09-10 05:55 UTC, suho commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRow.swift
> +    let article: Article
View cannot use `model` here. Within UI ticket, you just need to do:

```swift
// Don't
VStack(alignment: .leading) {
    Text(article.author.username)
    Text(article.formattedUpdatedAt)
        .foregroundColor(.gray)
}

// DO
VStack(alignment: .leading) {
    Text("author name") // dummy
    Text("September 10, 2021")
        .foregroundColor(.gray)
}

```

2021-09-10 05:55 UTC, suho commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
> +struct DummyProfile: Profile {
I think we can remove this, You just need to put direct value (String, Int, Bool) into View.

2021-09-10 06:35 UTC, suho commented on NimbleMedium/Sources/Supports/Extensions/Foundation/DateFormatter+MonthDayYear.swift
> +//  DateFormatter+MonthDayYear.swift
Please rename to `DateFormatter+Formats.swift` because you will put more date formatter in here

2021-09-10 06:35 UTC, suho commented on NimbleMedium/Sources/Constants/Constants+String.swift
> +    static let monthDayYearDateFormat: String = "MMMM dd, yyyy"
We only define a constant when we use it in different places. Currently, I think we just use it only in DateFormatter, so please remove this string here.

2021-09-10 08:02 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
> +
we don't need this change, please revert

2021-09-10 08:12 UTC, markgravity commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
> +
Don't know why it pops up, I tried to clear space or add break line but it doesn't work 🤪 
Even try to copy it from `develop`..

2021-09-10 08:15 UTC, minhnimble approved these changes
LGTM 🚀

2021-09-10 08:51 UTC, suho approved these changes

2021-09-10 09:21 UTC, merged