[#17] [Integrate] As a user, I can see the global feeds from the home screen when not logged in
nimblehq/nimble-medium-ios pull request #133
Opened 2021-09-14 03:04 UTC by markgravity

Resolved #17 

## What happened

Integrate Feeds in Home screen

## Insight

- [x] Populate the first page (index 0) of the global feeds data from server and show the loading indicator when first opening the `Home` screen without logging in.
- [x] Make sure each article contain: An author avatar url, an author name, an article created timestamp, an article title and an article content. 
- [x] When scrolling through the contents and reaching the bottom, trigger to load the next page of the global feeds data and show the loading indicator while doing so.
- [x] Stop the pagination load capability if there nothing more to load.
- [x] When there is an error while loading the articles, show a temporary toast message with text: `Something went wrong. Please try again later.`
- [x] If the app is unable to load any article, show a label at the center of the screen with text: `No Article`.

## Proof Of Work

First Load + Refresh + LoadMore

https://user-images.githubusercontent.com/17875522/133187847-b11823d3-e2ff-4f42-8592-6c4ffb5c0fdb.mov

No Article
<img src=https://user-images.githubusercontent.com/17875522/133187929-1f3b37e0-f506-4493-9b41-ef437c9ad2a6.png width=300>

2021-09-14 09:21 UTC, minhnimble commented on NimbleMedium.xcodeproj/project.pbxproj
> -				"$(PROJECT_DIR)/NimbleMediumTests/Sources/Mocks/Sourcery/AutoMockable.generated.swift",
why do we remove this script? 🤔

2021-09-14 09:21 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
> +    @State private var isFirstLoad: Bool = true
please add a line break above the `@State` vars for clean separation 🙏

2021-09-14 09:21 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
> +    let limit: Int = 10
I think we can remove the type declaration part `: Int` since when declaring as `let limit = 10` the complier can auto infer this constant as `Int` already 🙏

2021-09-14 09:21 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
> +             .gesture(dragGesture(geo: geo))
please fix the indentation here

2021-09-14 09:21 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
> +            .flatMapLatest { [weak self] in
please use `withUnretained` self here instead of `[weak self]`

2021-09-14 09:21 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
> +                self?.refreshTriggered() ?? .empty()
just curious why don't we use put the code in `func refreshTriggered()` directly in here? this function is used only once 🤔

2021-09-14 09:21 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
> +            }
please use `withUnretained` self here instead of `[weak self]`

2021-09-14 09:43 UTC, markgravity commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
> +                self?.refreshTriggered() ?? .empty()
@minhnimble I try to don't make our `init` too long and hard to read :grind

2021-09-14 10:59 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
> +                self?.refreshTriggered() ?? .empty()
@markgravity but then we have to add [weak self] and guard check as well? which is making the `refreshTriggered()` longer 😅. Or maybe you can pass the `owne`r from here into `refreshTriggered` function for reducing code a bit more. What do you think?

2021-09-14 11:02 UTC, markgravity commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
> +                self?.refreshTriggered() ?? .empty()
@minhnimble I updated it with `.withUnretained(self)` already 😁

2021-09-15 07:28 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
> +            }
can make this one line 😁
```suggestion
            .onAppear { viewModel.input.refresh() }
```

2021-09-15 07:28 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
> +
can remove this line break 😁

2021-09-15 07:28 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
> +        )
@markgravity from [here](https://github.com/nimblehq/nimble-medium-ios/pull/133#discussion_r708156414) what I mean is to pass the owner into to this function `refreshTriggered()` so that we can cleanup the `[weak self] in` and `guard let self = self else { return }` in here 🙏

2021-09-15 09:17 UTC, minhnimble approved these changes
LGTM 🚀

2021-09-17 03:06 UTC, suho commented on NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift
> +                        expect(didFinishRefresh.events.count) == 1
Please compare directly with the list of events to test the events and its value instead of counting the events here.

2021-09-17 03:06 UTC, suho commented on NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift
> +                            expect(didFinishLoadMore.events.first?.value.element) == false
Same here, please compare with the list of events instead of the first value

2021-09-17 03:06 UTC, suho commented on NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift
> +                            viewModel.loadMore()
With loadmore, please test with the case: calling loadMore multiple times (using RxTest)

2021-09-17 03:59 UTC, markgravity commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
> +    @State private var articles: [Article] = []
@suho it's what we're doing now? 🤔 
We bind view model to view by using
```
.onReceive(viewModel.output.isLoading) {
    loadingToast = $0
}
```

2021-09-17 04:00 UTC, markgravity commented on NimbleMedium/Sources/Constants/Constants.swift
> +        static let dateFormat = "MMMM, dd yyyy"
@suho Why? It's Article configuration? 🤔

2021-09-17 04:03 UTC, markgravity commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
> +    let loadMoreTrigger = PublishRelay<Void>()
I think it's ok here, cause we use `FeedsViewModelProtocol` to hide all implements and easier to test cause we can access all properties 🤔 
```swift
it("resets current offset") {
    expect(viewModel.currentOffset) == 0
}
```

2021-09-17 04:07 UTC, markgravity commented on NimbleMedium/Sources/Supports/Extensions/Foundation/Date+Format.swift
> +        let formatter = DateFormatter(with: format)
What do you mean `use static instance of Date Formatter`? 🙏

2021-09-17 04:12 UTC, markgravity commented on NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift
> +                        expect(didFinishRefresh.events.count) == 1
@suho it's void value, so we can't compare it directly 😁

2021-09-17 04:29 UTC, suho commented on NimbleMedium/Sources/Supports/Extensions/Foundation/Date+Format.swift
> +        let formatter = DateFormatter(with: format)
I mean that we should not use the function `format(_ format: String) -> String` as it will create a new DateFormatter instance everytime you call that. We should use a static instance instead.

2021-09-17 04:30 UTC, suho commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
> +    let loadMoreTrigger = PublishRelay<Void>()
Currently, we already apply about `input` and `output`, so we just need to test about the output.

2021-09-17 04:32 UTC, suho commented on NimbleMediumTests/Sources/Specs/Presentation/Modules/Feeds/FeedsViewModelSpec.swift
> +                        expect(didFinishRefresh.events.count) == 1
👍 Please check on other events if we can compare with event's element type.

2021-09-17 04:33 UTC, suho commented on NimbleMedium/Sources/Constants/Constants.swift
> +        static let dateFormat = "MMMM, dd yyyy"
What happens when we use this format in another screen?

2021-09-17 04:39 UTC, suho commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsView.swift
> +    @State private var articles: [Article] = []
You are using `Article` model directly in View, you should not do that. FeedsViewModel should transform model `Article` into a representative data that can be showed on View.

2021-09-20 10:27 UTC, suho approved these changes

2021-09-20 12:58 UTC, minhnimble requested changes

2021-09-20 12:58 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRow.swift
> +    @ObservedViewModel private var viewModel: FeedRowViewModelProtocol
just curious why don't we use injection here? 🤔

2021-09-20 12:58 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRowViewModel.swift
> +        updatedAt = Driver.just(article.updatedAt.format(with: .monthDayYear))
can create a UiModel for these attributes 🙏

2021-09-21 01:53 UTC, markgravity commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRow.swift
> +    @ObservedViewModel private var viewModel: FeedRowViewModelProtocol
@minhnimble cause our FeedsViewModel will store a list of FeedRowViewModelProtocol, then it will pass it when
```swift
ForEach(view.feedViewModels, id: \.output.id) {
    FeedRow(viewModel: $0)
        .padding(.bottom, 16.0)
}
```

2021-09-21 06:35 UTC, minhnimble approved these changes

2021-09-21 06:35 UTC, merged