[#19] [#75] As a user, I can see the article details screen when not logged in
nimblehq/nimble-medium-ios pull request #135
Opened 2021-09-14 07:16 UTC by markgravity

Resolved #19, #75

## What happened

- Create Feed Detail UI
- Create `Go to comments section` button

## Insight

Describe in detail how to test the changes; referenced documentation is welcome as well.

## Proof Of Work

Show us the implementation: screenshots, gif, etc.

2021-09-15 02:47 UTC, minhnimble commented on NimbleMedium/Sources/Supports/Helpers/SwiftUI/NavigationBarPrimaryStyle.swift
> +                            },
I think we can make this action one line 🙏

2021-09-15 08:25 UTC, markgravity commented on NimbleMedium/Sources/Presentation/Views/AuthorView.swift
> +    private let article: Article
@minhnimble I tried, but don't know why it doesnt work 🤔

2021-09-15 09:45 UTC, minhnimble approved these changes
LGTM 🚀

2021-09-15 10:09 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Views/AuthorView.swift
> +    private let article: Article
hmm okay, I guess we can do like this for now 🙏

2021-09-17 03:13 UTC, suho commented on NimbleMedium/Sources/Presentation/Views/AuthorView.swift
> +    private let article: Article
Please dont use model in View

2021-09-21 06:59 UTC, minhnimble requested changes
Need to fix conflicts 🛠🦀

2021-09-21 07:01 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/FeedDetail/FeedDetailView.swift
> +                Text(
Please add TODO for hardcoded text as well

2021-09-21 08:12 UTC, suho approved these changes

2021-09-21 09:24 UTC, minhnimble approved these changes
Just an optional suggestion, the rest LGTM 🚀

2021-09-21 09:24 UTC, minhnimble commented on NimbleMedium/Sources/Supports/Helpers/SwiftUI/NavigationBarPrimaryStyle.swift
> +                            label: { Image(R.image.backIcon.name) }
Just a small new suggestion in case you don't know that I think there is a system back icon you can use instead of importing a new pdf file:
<img width="903" alt="Screen Shot 2021-09-21 at 16 22 07" src="https://user-images.githubusercontent.com/70877098/134145997-661e1074-ba28-4bf1-bb4f-e684868bd4df.png">

The usage for applying a system icon:
```
Image(systemName: SystemImageName.xmark.rawValue)
```

2021-09-21 09:25 UTC, minhnimble requested changes
CI is failing, need to fix the issue 🛠🦀

2021-09-21 09:57 UTC, minhnimble approved these changes

2021-09-21 10:01 UTC, merged