[#56] [#21] [Integrate] As a user, I can see the article details screen when not logged in
nimblehq/nimble-medium-ios pull request #138
Opened 2021-09-15 03:00 UTC by markgravity

Resolved #56, #21

## What happened

- Integrate Feed Detail screen
- Link Feeds in Home screen with Feed Detail screen

## Insight

- [x] Populate data from the server for the selected article the `Article Details` screen, including the article title, the author avatar url, the author name, and the article created timestamp.
- [x] Show a native loading indicator in the middle of the screen while loading the article details.
- [x] When there is an error while loading the article details, show a temporary toast message with text: `Something went wrong. Please try again later.`
- [x] If the app is unable to load the article details, show a label at the center of the screen with text: `Unable to load the article`.
- [x] When the users tap on an article in the global feeds section from the `Home` screen, navigate to the `Feed Details` screen.
- [x] Once in the `Feed Details` screen, the users can tap on the `Back` button to go back to the previous screen.

## Proof Of Work

https://user-images.githubusercontent.com/17875522/133363174-f7d71f9f-a1ee-4f4b-86ad-2c90501aba4c.mov

Unable to load

<img src="https://user-images.githubusercontent.com/17875522/133363241-468cd56c-66a4-440f-9282-ec22ea708d4a.png" width=300>

2021-09-16 10:38 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
> +    }
Injecting `FeedDetailViewModel` in `FeedsViewModel` like this seems to not be the right way to do dependency injection here, I believe we should inject `FeedDetailViewModel` in `FeedDetailView` instead. We can pass the `article.slug` directly to the `FeedDetailView` and call the above injection function in the `FeedDetailView` like below. What do you think?


```
// In FeedDetailView
private var articleSlug: String

init(articleSlug: String) {
    self.articleSlug = articleSlug
}

@ObservedViewModel private var viewModel: FeedDetailViewModelProtocol.self = Resolver.resolve(
              FeedDetailViewModelProtocol.self,
              args: articleSlug
          )
```

2021-09-17 03:10 UTC, minhnimble approved these changes

2021-09-17 04:17 UTC, minhnimble commented
Need to fix CI build failed issue 🦀🛠

2021-09-17 04:18 UTC, minhnimble requested changes
Need to fix CI build failed issue 🦀🛠

2021-09-17 11:27 UTC, minhnimble commented
I tested the app and found an issue that the left menu is still openable in Article Details screen by dragging the screen from left to right. Please help check


https://user-images.githubusercontent.com/70877098/133774997-e0d4b283-902a-458e-bcaa-23e5b9c88211.MP4

2021-09-20 09:29 UTC, markgravity commented
> I tested the app and found an issue that the left menu is still openable in Article Details screen by dragging the screen from left to right. Please help check this issue 🙏
> 
>  RPReplay_Final1631877832.MP4

@minhnimble let me create an issue for this bug 🙏

2021-09-20 09:58 UTC, minhnimble commented
@markgravity please follow our team convention for creating an issue by adding one more label about priority, put it into the project `Ready for Development` column and set the latest milestone for it for keeping track purpose, thanks 🙏

2021-09-20 10:13 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/FeedDetail/FeedDetailViewModel.swift
> +                owner.$didFetchArticle.accept(())
you can send the article object to the view and handle each attribute in the bind block. No need to send each attribute from VM 🙏

2021-09-21 09:26 UTC, minhnimble commented
Need to fix conflicts 🛠🦀

2021-09-22 08:23 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/FeedDetail/FeedDetailView.swift
>      struct Content: View {
just curious why don't we put the `Content` struct directly in `FeedDetailView` as a View variable? 🤔

2021-09-22 08:23 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRow.swift
>  extension FeedRow.Content {
same for the `FeedRow.Content` struct 🤔

2021-09-22 09:16 UTC, minhnimble approved these changes
The rest LGTM 🚀

2021-09-22 09:16 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/FeedDetail/FeedDetailUIModel.swift
> +//  FeedDetailUIModel.swift
since this is an extension please name it `FeedDetail+UIModel.swift` and remove the swiftLint check 🙏

2021-09-22 09:16 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRowUIModel.swift
>  //  NimbleMedium
same here

2021-09-23 03:17 UTC, suho commented on NimbleMedium/Sources/Presentation/Modules/FeedDetail/FeedDetailView+UIModel.swift
> +            authorName = article.author.username
the View Model should contain these code, not the UIModel.

2021-09-23 03:17 UTC, suho commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRowViewModel.swift
> +        self.uiModel = .just(uiModel)
We should create `FeedRow.UIModel` inside `FeedRowViewModel`. The `FeedRowViewModel` is responsible for create UIModel

2021-09-23 04:54 UTC, suho commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRow.swift
> +                Text("empty")
empty text with red color is not a good UI, please use empty view instead

2021-09-23 04:54 UTC, suho commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedRow/FeedRowViewModel.swift
> +        self.uiModel = .just(
Please emit `self.`

2021-09-23 04:54 UTC, suho commented on NimbleMedium/Sources/Presentation/Modules/Feeds/FeedsViewModel.swift
> +                owner.$feedRowViewModels.accept(self.$feedRowViewModels.value + $0.viewModels)
Please use `owner` instead

2021-09-23 09:10 UTC, minhnimble commented
@markgravity can we squash all duplicated name commits into 1 commit? 😁

<img width="732" alt="Screen Shot 2021-09-23 at 16 09 07" src="https://user-images.githubusercontent.com/70877098/134481665-29a39ee5-8306-4b9a-ab9e-b4e93a19a526.png">

2021-09-24 02:04 UTC, markgravity commented
> @markgravity can we squash all duplicated name commits into 1 commit? 😁
> 
> <img alt="Screen Shot 2021-09-23 at 16 09 07" width="732" src="https://user-images.githubusercontent.com/70877098/134481665-29a39ee5-8306-4b9a-ab9e-b4e93a19a526.png">

In fact, they have a diff content 😁 
<img width="373" alt="Screen Shot 2021-09-24 at 09 02 55" src="https://user-images.githubusercontent.com/17875522/134607237-ab09519e-07b3-4038-b9b4-c13348eaa0de.png">

2021-09-24 02:40 UTC, minhnimble requested changes

2021-09-24 02:40 UTC, minhnimble commented on Podfile.lock
> +COCOAPODS: 1.10.1
@markgravity please update your local pod to latest stable version, we should not downgrade version like this, except when accidentally commit the beta version of the pod up 🙏

2021-09-24 02:47 UTC, minhnimble approved these changes
LGTM 🚀

2021-09-24 03:12 UTC, suho approved these changes

2021-09-24 03:14 UTC, merged