[#29] As a user, I can see the article details screen when not logged in
nimblehq/nimble-medium-ios pull request #140
Opened 2021-09-15 07:45 UTC by markgravity

Resolved #29 

## What happened

create comments screen UI

## Insight

- [x] Add the top navigation bar and the `Back` button by reusing the UI layout from #19.
- [x] Update the navigation bar title with text: `Comments History`.
- [x] Add a vertical table view for containing the list of comments below the top navigation bar.
- [x] Create a comment table view cell with UI layout: A comment body label, a commenter avatar image view,  a commenter name label, A comment `updatedAt` date label as shown in the below design.
- [x] The comment table view cell's height should be dynamic based on the comment's content (body).

## Proof Of Work

![Uploading Screen Shot 2021-09-15 at 14.42.12.png…]()

2021-09-17 06:39 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentRow/FeedCommentRow.swift
> +                .foregroundColor(.gray)
please add TODO for hardcoded values 🙏

2021-09-17 06:39 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentsView.swift
> +                    ForEach(1...3, id: \.self) { _ in
please add TODO for hardcoded values 🙏

2021-09-17 06:39 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentRow/FeedCommentRow.swift
> +            Text("cypress")
Just curious how do we handle long name here, is it going to go exceed the screen? 🤔

2021-09-20 09:45 UTC, markgravity commented on NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentRow/FeedCommentRow.swift
> +            Text("cypress")
@minhnimble  Still looks decent 😁 
<img width="348" alt="Screen Shot 2021-09-20 at 16 45 19" src="https://user-images.githubusercontent.com/17875522/133983150-fcf242f7-9468-497a-ba17-ae69042ed93f.png">

2021-09-21 08:08 UTC, suho approved these changes

2021-09-21 08:16 UTC, minhnimble approved these changes
LGTM 🚀

2021-09-24 02:49 UTC, minhnimble requested changes

2021-09-24 02:49 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentRow/FeedCommentRow.swift
> +
can remove this line break 🙏

2021-09-24 02:49 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/FeedComments/FeedCommentsView.swift
> +        Content(view: self)
Please bring the sub-views from the `Content` struct into this var `body` directly, thanks 🙏

2021-09-24 02:55 UTC, minhnimble approved these changes
LGTM 🚀

2021-09-24 03:46 UTC, merged