[#53] As a user, I can see my profile briefing in the left menu header
nimblehq/nimble-medium-ios pull request #146
Opened 2021-09-20 12:38 UTC by minhnimble

Resolved #53

## What happened

Once the users logged in the application successfully, opening the left navigation menu will show a brief summary of the user information in the menu header, which includes: the user avatar and the username.

## Insight

- [x] After the users logged in successfully, store the current user profile to be used later in the application session.
- [x] Populate the current user profile including the user avatar and the username on the left menu header section.
- [x] Make sure each time users open to view the left menu, the app shows the latest current user profile.
- [x] If there is any error loading user data or some data is not available, show the default user avatar and/or the default username with text: `Current User`.
- [x] Unit tests added.

## Proof Of Work

Flows:

https://user-images.githubusercontent.com/70877098/134003401-282bba7b-4400-4ae7-9774-530f570bb6f2.mov

Unit tests:

<img width="1432" alt="Screen Shot 2021-09-20 at 19 34 48" src="https://user-images.githubusercontent.com/70877098/134003318-7cf744c5-c318-428b-8371-de68b456838e.png">

2021-09-21 08:22 UTC, suho requested changes

2021-09-21 08:22 UTC, suho commented on NimbleMedium/Sources/Data/Models/CodableUser.swift
> +
We should move this code into View Model, a `Model` should not care about the `UI Model` (it's related to View).

2021-09-21 08:22 UTC, suho commented on NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderView+UiModel.swift
> +    struct UiModel: Equatable {
Should it be `UIModel` or `UiModel`? 🤔

2021-09-21 08:30 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderView+UiModel.swift
> +    struct UiModel: Equatable {
@suho I am actually fine with both way, the Android team is using `UiModel` so that is why it applies here. If you insist I think we can definitely use `UIModel` no problem 😁

2021-09-21 09:15 UTC, minhnimble commented on NimbleMedium/Sources/Data/Models/CodableUser.swift
> +
@suho this is a part of DataModel mapping to UIModel so I am going to put it in UIModel, sounds good? 😁

2021-09-22 07:18 UTC, markgravity commented on NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderView.swift
>      }
I think we can improve these ones a little bit, what do you think about this approach? 🤔 
```swift
@State private var uiModel: UIModel?

var body: some View {
    ZStack(alignment: .center) {
        Color.green.edgesIgnoringSafeArea(.all)
        if let uiModel = uiModel {
            // Change to function and pass uimodel into it
            authenticatedMenuHeader(uiModel: uiModel)
        } else {
            unauthenticatedMenuHeader
        }
    }
    .bind(viewModel.output.uiModel, to: _uiModel)
}

func authenticatedMenuHeader(uiModel: UIModel) -> some View {
    VStack(alignment: .center) {
        if let url = uiModel.avatarURL {
            WebImage(url: url)
                .placeholder { defaultAvatar }
                .resizable()
                .frame(width: 100.0, height: 100.0)
                .clipShape(Circle())
        } else {
            defaultAvatar
        }
        Text(uiModel.username)
            .foregroundColor(.white)
            .fontWeight(.bold)
            .lineLimit(2)
            .multilineTextAlignment(.center)
            .padding()
    }
}
```

2021-09-22 07:18 UTC, markgravity commented on NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderView.swift
> +            if let url = try? avatarUrl?.asURL() {
I think we should convert avatar to URL into our UIModel, what do you think? 🤔

2021-09-22 07:18 UTC, markgravity commented on NimbleMediumTests/Sources/Specs/Presentation/Modules/SideMenuHeader/SideMenuHeaderViewModelSpec.swift
> +                    .asSignal(onErrorJustReturn: true)
You can simply `.just(true)` here 👍

2021-09-22 07:18 UTC, markgravity commented on NimbleMediumTests/Sources/Specs/Presentation/Modules/SideMenuHeader/SideMenuHeaderViewModelSpec.swift
> +                        }
You can use my improvement for this 🙏 
```swift
.just(
    user,
    on: scheduler,
    at: 10
)
```

and for error
```swift
.error(
    anError,
    on: scheduler,
    at: 10
)
```

2021-09-22 07:44 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderView.swift
>      }
yeah your new `bind` extension is only available in the recent PRs, not when I implemented this 👍

2021-09-22 07:47 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderView+UiModel.swift
> +    }
@markgravity I want to show as map from one Model to UIModel so that is why I write a computed var here. I don't really think it is necessary to add `init` so I will keep the current implementation 🙏

2021-09-22 08:30 UTC, markgravity approved these changes
LGTM

2021-09-23 03:24 UTC, suho commented on NimbleMedium/Sources/Presentation/Modules/SideMenu/SideMenuHeader/SideMenuHeaderView+UIModel.swift
> +            }
The `SideMenuHeaderViewModel` should contain this convert logic. As we discussed before. ViewModel is responsible for convert or transforms the Model to UIModel. Not put everything into UIModel

2021-09-23 04:11 UTC, suho approved these changes

2021-09-23 04:36 UTC, merged