[66] As a user, I can see the list of created articles from the profile screen
nimblehq/nimble-medium-ios pull request #159
Opened 2021-09-28 08:17 UTC by markgravity

Resolved #66

## What happened

Add GetCreatedArticles use case

## Insight

- Update cocoapod version in `Gemfile` to match with version in `Podfile.lock`

## Proof Of Work

Request
```
*** Overview *** 
URL https://conduit.productionready.io/api/articles?author=markg&limit=25
Method GET
Response Code -
Request Start Time Sep 28 2021 - 15:14:28
Duration 848ms

*** Request Header *** 
User-Agent Nimble Medium - Staging/1.2.0 (co.nimblehq.nimble-medium-stag; build:1; iOS 14.5.0) Alamofire/5.4.4
Accept-Language en;q=1.0
Accept-Encoding br;q=1.0, gzip;q=0.9, deflate;q=0.8

*** Request Body *** 
-

*** Response Header *** 
-

*** Response Body *** 
-

------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------
```

Subscribe Log
```
2021-09-28 15:14:28.482: GetCreatedArticlesUseCase -> subscribed
2021-09-28 15:14:30.611: GetCreatedArticlesUseCase -> Event next([NimbleMedium.DecodableArticle(slug: "Welcome-to-RealWorld-project", title: "Welcome to RealWorld project", description: "Exemplary fullstack Medium.com clone powered by React, Angular, Node, Django, and many more", body: "See how the exact same Medium.com clone (called Conduit) is built using different frontends and backends. Yes, you can mix and match them, because they all adhere to the same API spec", tagList: ["introduction", "welcome"], createdAt: 2021-09-25 18:17:54 +0000, updatedAt: 2021-09-25 18:17:54 +0000, favorited: false, favoritesCount: 35, apiAuthor: NimbleMedium.DecodableProfile(username: "Gerome", bio: nil, image: Optional("https://realworld-temp-api.herokuapp.com/images/demo-avatar.png"), _following: DefaultCodable.Default<DefaultCodable.False>(wrappedValue: false)))])
2021-09-28 15:14:30.611: GetCreatedArticlesUseCase -> Event completed
2021-09-28 15:14:30.611: GetCreatedArticlesUseCase -> isDisposed
```

2021-09-28 10:38 UTC, minhnimble approved these changes
LGTM 🚀

2021-09-28 10:39 UTC, minhnimble commented
Just curious, we don't have any sample request/response log? how can you verify if the API works then 😅

2021-09-29 03:43 UTC, suho approved these changes

2021-09-29 03:43 UTC, suho commented on NimbleMediumTests/Sources/Specs/Domain/UseCases/Article/GetCreatedArticlesUseCaseSpec.swift
> +        var usecase: GetCreatedArticlesUseCase!
```suggestion
        var useCase: GetCreatedArticlesUseCase!
```

2021-09-29 05:32 UTC, minhnimble requested changes
Need to fix this PR's conflict 🙏

2021-09-29 09:21 UTC, minhnimble approved these changes

2021-09-29 09:22 UTC, minhnimble commented on NimbleMediumTests/Sources/Specs/Domain/UseCases/Article/GetCreatedArticlesUseCaseSpec.swift
> +        var usecase: GetCreatedArticlesUseCase!
@markgravity we still have unresolved conversation here =))

2021-10-01 02:56 UTC, merged