[#69] As a user, I can see the list of favorited articles from the profile screen when not logged
nimblehq/nimble-medium-ios pull request #163
Opened 2021-09-29 07:59 UTC by markgravity

Resolved #69 

## What happened

Create Favourited Articles List UI in Profile screen

## Insight

- Create `AvatarView` to display an avatar and refactor related code

## Proof Of Work
<img width="539" alt="Screen Shot 2021-09-29 at 14 56 24" src="https://user-images.githubusercontent.com/17875522/135227246-1cdaa515-17de-4e07-ba31-37c570ee3fce.png">

2021-10-04 09:28 UTC, minhnimble approved these changes
the rest LGTM 🚀

2021-10-04 09:28 UTC, minhnimble commented on NimbleMedium/Resources/en.lproj/Localizable.strings
> +"userProfile.favouritedArticles.title" = "Favourited Articles";
sort this line please 😅

2021-10-04 10:18 UTC, suho commented on NimbleMedium/Sources/Presentation/Views/AvatarView.swift
> +
Why do you need to break a new line here?

2021-10-05 02:04 UTC, markgravity commented on NimbleMedium/Sources/Presentation/Modules/UserProfile/UserProfileView.swift
> +        @ObservedObject fileprivate var theme = NavTabViewTheme()
@suho I tried with **@State** but it doesn't work, also it follows their [suggestion](https://github.com/xmartlabs/PagerTabStripView#customize-selected-and-highlighted-items)

2021-10-05 02:07 UTC, markgravity commented on NimbleMedium.xcodeproj/project.pbxproj
> +			repositoryURL = "https://github.com/markgravity/PagerTabStripView.git";
@suho I dont think we should mess our `nimblehq`, I gonna create a PR for them to merge this fork. 
So I will update the URL when the fork is mergered

2021-10-05 02:11 UTC, markgravity commented on NimbleMedium/Sources/Presentation/Views/AvatarView.swift
> +
@suho to separate between setup and return section 😁 
```swift
func size(_ value: CGFloat) -> Self {
  // Setup
  var view = self
  view.size = value

  // Return
  return view
}
```

2021-10-05 02:48 UTC, minhnimble approved these changes

2021-10-07 02:50 UTC, suho commented on NimbleMedium.xcodeproj/project.pbxproj
> +			repositoryURL = "https://github.com/markgravity/PagerTabStripView.git";
Please use `nimblehq` as this repository is in the nimblehq org.

2021-10-08 02:40 UTC, suho requested changes

2021-10-08 02:40 UTC, suho commented on NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "repositoryURL": "https://github.com/markgravity/PagerTabStripView.git",
Please rebase from #169 to use the repository from nimblehq

2021-10-08 02:45 UTC, markgravity commented on NimbleMedium.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "repositoryURL": "https://github.com/markgravity/PagerTabStripView.git",
@suho it's the root branch of #169 so let skip it and then it will be updated at #169 😅

2021-10-08 04:24 UTC, merged