[#230] Fix: Check danger comments on pull request #230
nimblehq/nimble-medium-ios pull request #253
Opened 2021-11-18 02:31 UTC by minhnimble

Resolved #230

## What happened

Currently, the danger's comment on a pull request is empty without xcov report. The danger's comment should show xcov report with code coverage.

## Insight

NA

## Proof Of Work

NA

2021-11-19 03:25 UTC, suho requested changes
Let's focus on the bug, if the bug is related to `only_project_targets` and `include_targets`, then please fix only that, people can know the exactly what is the cause

2021-11-19 03:25 UTC, suho commented on .github/workflows/automatic_pull_request_review.yml
> +      run: bundle exec danger
`secrets.GITHUB_TOKEN` is the same with `github.token`, so don't need to update here, also please add a new line at the end of the file also

2021-11-20 06:27 UTC, minhnimble commented
> Let's focus on the bug, if the bug is related to only_project_targets and include_targets, then please fix only that, people can know the exactly what is the cause

@suho other changes are necessary to make sure all tests reports returned correctly for showing using latest stable gems versions. Previously when there are no UI tests the report logged `All case` tests as 0.

2021-11-22 02:44 UTC, suho approved these changes

2021-11-22 02:47 UTC, markgravity approved these changes

2021-11-22 04:31 UTC, merged