[#7] [Feature] [UI] Create default top navigation bar
nimblehq/nimble-medium-ios pull request #36
Opened 2021-08-10 07:28 UTC by markgravity

Resolved #7 

## What happened

When first opening the application, the users will be able to see the default top navigation bar.

## Insight

- Add navigation bar modifier to handle navigation background and title color
- Add Screen view to wrap up navigation bar and content

## Proof Of Work

<img width="300" alt="Screen Shot 2021-08-10 at 14 16 31" src="https://user-images.githubusercontent.com/17875522/128826111-c1040aae-1575-4b54-8c06-d046c441bf32.png">

2021-08-10 08:36 UTC, minhnimble reviewed
Nice work, just a few minor comments

2021-08-10 08:36 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Views/Screen.swift
> +                    title ?? "",
Please create a global constant for empty string name `EMPTY_STRING` for the usage here and future usage, thanks 🙏

2021-08-10 08:36 UTC, minhnimble commented on NimbleMedium/Sources/Presentation/Modules/Home/HomeView.swift
> +            Text("This is home")
Just an optional that we can add a `TODO` here noting that we will remove this `Text` at a later time, this is just for testing purpose only 😁

2021-08-10 08:57 UTC, minhnimble commented on NimbleMedium/Sources/Constants/Constants.swift
> +let EMPTY_STRING = ""
or we can go with Apple's best practice which is the camelCase version - `emptyString` 😁 disable lint at every place seems a bit annoying I think

2021-08-10 09:00 UTC, suho commented on NimbleMedium/Sources/Constants/Constants.swift
> +let EMPTY_STRING = ""
I prefer
```swift
extension String {

   static let empty = ""
}
```

2021-08-10 09:01 UTC, markgravity commented on NimbleMedium/Sources/Constants/Constants.swift
> +let EMPTY_STRING = ""
@minhnimble how about this? 🤔 
```swift
title.orEmpty()
```

2021-08-10 09:07 UTC, minhnimble commented on NimbleMedium/Sources/Constants/Constants.swift
> +let EMPTY_STRING = ""
@markgravity can write an extension for checking if a string is empty `orEmpty()` as well 👍. But we still need an empty string constant to work with. Can use @suho for the constant declaration 🙏

2021-08-10 09:13 UTC, markgravity commented on NimbleMedium/Sources/Constants/Constants.swift
> +let EMPTY_STRING = ""
Let me combine both  👍

2021-08-10 09:49 UTC, suho commented on NimbleMedium/Sources/Presentation/Views/Screen.swift
> +    }
```suggestion
    init(
        title: String? = nil,
        titleColor: Color = .white,
        @ViewBuilder content: () -> Content
    ) {
        self.content = content()
        self.title = title
        self.titleColor = titleColor
    }
```

2021-08-10 09:49 UTC, suho commented on NimbleMedium/Sources/Presentation/Views/Screen.swift
> +    private let content: Content
I would prefer to define the property like the code below as we usually create and use the view in `body`
```suggestion
private let content: () -> Content
```

In some cases, we need to duplicate the content ([GridStack](https://www.hackingwithswift.com/books/ios-swiftui/custom-containers)), so don't need to create the view in init

2021-08-10 09:49 UTC, suho commented on NimbleMedium/Sources/Presentation/Views/Screen.swift
> +struct Screen<Content>: View where Content: View {
```suggestion
struct Screen<Content: View>: View {
```

2021-08-10 09:49 UTC, suho commented on NimbleMedium/Sources/Supports/Extensions/NavigationBarModifier.swift
> +        self.modifier(
Can we omit `self.`?

2021-08-10 09:49 UTC, suho commented on NimbleMedium/Sources/Supports/Extensions/String.swift
> +}
We should move this into the `Constants` folder.

2021-08-10 09:49 UTC, suho commented on NimbleMedium/Sources/Supports/Extensions/String.swift
> +}
And update the name of this file and move to Foundation folder: `Extensions/Foundation/Optional+String.swift`

2021-08-10 09:49 UTC, suho commented on NimbleMedium/Sources/Supports/Extensions/NavigationBarModifier.swift
> +        titleColor: Color = .white) -> some View {
```suggestion
    func navigationBarColor(
        backgroundColor: Color = .clear,
        titleColor: Color = .white
     ) -> some View {
```

2021-08-10 10:14 UTC, markgravity commented on NimbleMedium/Sources/Presentation/Views/Screen.swift
> +    private let content: Content
@suho  Hmm I think we should use it correctly, for example
```swift
struct HomeView: View {

    private let content: () -> Content
    @State var buttonTitle: String = "Append me"

    var body: some View {
        print("Rebuild")

        // TODO: Update the title and its content in Home integrate task
        return Screen(title: Localizable.homeTitle()) {
            content()
            Button {
                buttonTitle += "1"
            } label: {
                Text(buttonTitle)
            }

        }
    }
}
```
In this case, every time we click the button, the body will be recalled. Then if we use `content()` here, it will be re-created also

2021-08-10 10:18 UTC, markgravity commented on NimbleMedium/Sources/Supports/Extensions/String.swift
> +}
What kind of extension that we should put into `Foundation`? 🤔

2021-08-10 10:31 UTC, suho commented on NimbleMedium/Sources/Presentation/Views/Screen.swift
> +    private let content: Content
I think It's normal.
From this link: https://www.hackingwithswift.com/books/ios-swiftui/custom-containers. It defines `let content: (Int, Int) -> Content`.

also, with this code, another views will be re-created, right?
```swift
var body: some View {
       Screen(title: Localizable.homeTitle()) {
            content()
            Button {
                buttonTitle += "1"
            } label: {
                Text(buttonTitle) // <--- everytime we press the button, it will re-created the Text?
            }
            Text("Another Text") // <--- it will re-created the Text?
            HStack {} // <--- it will re-created the HStack?
        }
    }
```

Correct me if I'm missing something :D

2021-08-10 10:50 UTC, suho commented on NimbleMedium/Sources/Presentation/Views/Screen.swift
> +    private let content: Content
@markgravity However, I think we can go with both ways. In some cases like the GridStack in the article, we can use `let content: (Int, Int) -> Content`, otherwise, we can use `let content: Content`
Not a big deal here :D

2021-08-10 11:07 UTC, minhnimble commented
Need to fix CI failed issue 🦀🛠

2021-08-11 02:59 UTC, minhnimble commented
@markgravity I don't see any CI check after you force-push your branch. Your claim [here](https://github.com/nimblehq/nimble-medium-ios/pull/14#discussion_r684963784) doesn't seem to be correct 😔. We need to add `push` events for our CI, I will reopen the setup CI ticket 🙏

2021-08-11 03:05 UTC, minhnimble approved these changes
LGTM 🚀

2021-08-11 04:13 UTC, markgravity commented
@suho @minhnimble I did a bit of refactoring to make our navigation bar configure easier and more readable. Please help me to re-review it 🙏 
And sorry for this re-request, I did it after learning something new in SwiftUI 😁 

Before
```swift
Screen(title: "Home") {
    Text("This home screen")
        .toolbar {
            // Add more navigation items here
        }
}
```

After
```swift
Screen() {
    NavigationBar (title: "Home") {
        // Add more navigation items here
    }
    Text("This home screen")
}
```

2021-08-11 04:18 UTC, minhnimble approved these changes
> @suho @minhnimble I did a bit of refactoring to make our navigation bar configure easier and more readable. Please help me to re-review it 🙏
> And sorry for this re-request, I did it after learning something new in SwiftUI 😁
> 
> Before
> 
> ```swift
> Screen(title: "Home") {
>     Text("This home screen")
>         .toolbar {
>             // Add more navigation items here
>         }
> }
> ```
> 
> After
> 
> ```swift
> Screen {
>     NavigationBar(title: "Home") {
>         // Add more navigation items here
>     }
>     Text("This home screen")
> }
> ```

@markgravity don't worry we are all learning, nice work 👍 Just a friendly reminder that you might need to update the P.o.W if needed since we are changing the way to create the navigation bar a bit🙏

2021-08-11 04:55 UTC, suho commented
> @suho @minhnimble I did a bit of refactoring to make our navigation bar configure easier and more readable. Please help me to re-review it 🙏
> And sorry for this re-request, I did it after learning something new in SwiftUI 😁
> 
> Before
> 
> ```swift
> Screen(title: "Home") {
>     Text("This home screen")
>         .toolbar {
>             // Add more navigation items here
>         }
> }
> ```
> 
> After
> 
> ```swift
> Screen {
>     NavigationBar(title: "Home") {
>         // Add more navigation items here
>     }
>     Text("This home screen")
> }
> ```

I would not prefer this way, because you are not familiar with declarative syntax. SwiftUI uses a declarative syntax, so it's fine to have this code:
```swift
Text("This home screen")
    .toolbar {  ... }
// this "toolbar" way is easier and readable for people who already knew SwiftUI :D.
```
If the codes are not easier or readable for you, so you need to learn and understand more about **declarative syntax**.
Don't do something unusual this time, new SwiftUI members (or even people who have experience with SwiftUI) when joining the project will take time to check the source code to understand. We can do some customize later after all members are familiar with SwiftUI and we have a convention with SwiftUI.

In this project, let's keep the SwiftUI style first, don't try to customize it. We need to understand deeply the SwiftUI first.

In conclusion, I prefer to use `NavigationView`, `.navigationBarTitle`, `. navigationBarColor `, `. toolbar` directly in the `HomeView`. We don't need `Screen` and `NavigationBar` at this time :D

2021-08-11 05:00 UTC, suho requested changes
Please check my comment above ☝️

2021-08-11 05:13 UTC, markgravity commented
@suho 
> I would not prefer this way, because you are not familiar with the declarative syntax, we need to learn it. SwiftUI uses a declarative syntax, so it's fine to have this code:

I don't mean the syntax there, the meaning I wanna mention here is that when we use a view modifer you will think it will modify that view.
But with `toolbar`, it modifies the navigation bar, but it's called from `Text` that it makes me look weird

> In this project, let's keep the SwiftUI style first, don't try to customize it. We need to understand deeply the SwiftUI first.

If we agree to stick with the original stuff, let me revert these 😢 
cc: @minhnimble

2021-08-11 05:18 UTC, suho commented
> but it's called from Text that it makes me look weird

@markgravity That's why we need to learn SwiftUI to understand more. Why did Apple put the toolbar like that, why don't they implement SwiftUI like your way :D SwiftUI also has `NavigationLink`, you will also put it into the content block of NavigationView. So lot of new thing to learn, don't try to ignore it :D

2021-08-11 09:59 UTC, suho approved these changes

2021-08-12 02:13 UTC, merged